Actividades/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base  import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/notas/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("notas/", include("notas.urls"))
]

notas/urls.py
from django.urls import path
from . import views 

app_name = 'notas'

urlpatterns = [
    path("", views.ListaView.as_view(), name="lista"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("crear/", views.CrearView.as_view(), name="crear"),
    path("<int:pk>/editar/", views.EditarView.as_view(), name="editar"),
    path("<int:pk>/eliminar/", views.EliminarView.as_view(), name="eliminar"),
]

notas/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Nota(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField("Contenido de la nota...")
    fecha_publicacion = models.DateTimeField("hola", auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete= models.CASCADE, related_name="notas")

    def __str__(self):
        return self.titulo
    

notas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Nota
from django.db.models import F
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class ListaView(LoginRequiredMixin, generic.ListView):
    model = Nota
    template_name = "lista.html"
    context_object_name = "lista_notas"

    def get_queryset(self):
        return Nota.objects.filter(usuario=self.request.user).order_by("-fecha_publicacion")

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Nota
    template_name = "detalle.html"

    def dispatch(self, request, *args, **kwargs):
        nota = self.get_object()
        if nota.usuario != self.request.user:
            # Aquí hacemos redirect a la lista
            return redirect('notas:lista')
        return super().dispatch(request, *args, **kwargs)

class CrearView(LoginRequiredMixin, CreateView):
    model = Nota
    template_name = "formulario.html"
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('notas:lista')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

class EditarView(LoginRequiredMixin, UpdateView):
    model = Nota
    template_name = "editar.html"
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('notas:lista')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.usuario != self.request.user:
            return redirect('notas:lista')
        return super().dispatch(request, *args, **kwargs)

class EliminarView(LoginRequiredMixin, DeleteView):
    model = Nota
    success_url = reverse_lazy('notas:lista')
    template_name = "detalle.html"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.usuario != self.request.user:
            return redirect('notas:lista')
        return super().dispatch(request, *args, **kwargs)

notas/templates/detalle.html
<!DOCTYPE html>
<html lang="es">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Detalle de la nota</title>
      {% load static %}
      <link rel="stylesheet" href="{% static 'detalle.css' %}">
  </head>
  <body>
    <div style="text-align: right; padding: 10px;"></div>

    <h1>Detalle de la nota</h1>
    <h1>{{ nota.titulo }}</h1>
    <h2>{{ nota.contenido }}</h2>

    <div>
      <form action="{% url 'notas:eliminar' nota.id %}" method="POST" style="display:inline;">
        {% csrf_token %}
        <button type="submit" class="delete">Eliminar</button>
      </form>

      <button  class="btn-link"><a href="{% url 'notas:editar' nota.id %}">Editar</a></button>

      <form action="{% url 'logout' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
      </form>
    </div>
  </body>
</html>

notas/templates/editar.html
<!DOCTYPE html>
<html lang="es">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Detalle de la nota</title>
      {% load static %}
      <link rel="stylesheet" href="{% static 'editar.css' %}">
  </head>
  <body>
    <h1>Edicion</h1>
    <div class="card">
      <h2>Nota original</h2>
      <div class="note-content">
        <p><strong>Título:</strong></p>
        <p>{{ nota.titulo }}</p>
        <br>
        <p><strong>Contenido:</strong></p>
        <p>{{ nota.contenido }}</p>
      </div>
    </div>

    <form method="post">
      {% csrf_token %}
      <fieldset>
          <legend><h1>Editar nota</h1></legend>
          {{ form.as_p }}

          <button type="submit">Guardar cambios</button>
          <a href="{% url 'notas:lista' %}" class="cancelar">Cancelar</a>
      </fieldset>
    </form>


</body>
</html>

notas/templates/formulario.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de la pregunta</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'formulario.css' %}">
</head>
<body>
        <h2>Crear nueva nota</h2>

    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

      <button type="submit">Publicar</button>
    </form>
</body>
</html>

notas/templates/lista.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lista.css' %}">
    <title>Notas</title>
  </head>

  <body>
    <h1>Listado de notas</h1>
    {% if lista_notas %}
    <ul>
      {% for nota in lista_notas %}
      <li><a href="{% url 'notas:detail' nota.id %}">{{ nota.titulo }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No se encontraron notas</p>
    {% endif %}
    <a href="{% url 'notas:crear' %}" class="crear-btn">Crear una pregunta</a>
    <div style="text-align: right; padding: 10px;">
      <form action="{% url 'logout' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
      </form>
    </div>

  </body>
</html>